project_id = "cwhjqthurdxltmacghpj"

[functions.analyze-image]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.ingest-document]
verify_jwt = false

[functions.security-chat]
verify_jwt = false
